from django.core.management.base import BaseCommand
from main.models import PrintCost

print_costs = [
    {
        'color': 'light',
        'quantity_range_low':1,
        'quantity_range_high':23,
        'color_1_cost':4.8,
        'color_2_cost':5.1,
        'color_3_cost':5.4,
        'color_4_cost':5.7,
        'color_5_cost':6,
        'color_6_cost':None,
        'color_additional_cost':None,
    },
    {
        'color': 'light',
        'quantity_range_low':24,
        'quantity_range_high':35,
        'color_1_cost':3.6,
        'color_2_cost':3.9,
        'color_3_cost':4.2,
        'color_4_cost':4.5,
        'color_5_cost':4.8,
        'color_6_cost':None,
        'color_additional_cost':None,
    },
    {
        'color': 'light',
        'quantity_range_low':36,
        'quantity_range_high':71,
        'color_1_cost':1.62,
        'color_2_cost':2.1,
        'color_3_cost':2.4,
        'color_4_cost':2.7,
        'color_5_cost':3,
        'color_6_cost':3.3,
        'color_additional_cost':0.3,
    },
    {
        'color': 'light',
        'quantity_range_low':72,
        'quantity_range_high':143,
        'color_1_cost':1.02,
        'color_2_cost':1.5,
        'color_3_cost':1.8,
        'color_4_cost':2.1,
        'color_5_cost':2.4,
        'color_6_cost':2.7,
        'color_additional_cost':0.3,
    },
    {
        'color': 'light',
        'quantity_range_low':144,
        'quantity_range_high':287,
        'color_1_cost':0.9,
        'color_2_cost':1.32,
        'color_3_cost':1.62,
        'color_4_cost':1.92,
        'color_5_cost':2.22,
        'color_6_cost':2.52,
        'color_additional_cost':0.3,
    },
    {
        'color': 'light',
        'quantity_range_low':288,
        'quantity_range_high':499,
        'color_1_cost':0.78,
        'color_2_cost':1.02,
        'color_3_cost':1.2,
        'color_4_cost':1.38,
        'color_5_cost':1.56,
        'color_6_cost':1.74,
        'color_additional_cost':0.18,
    },
    {
        'color': 'light',
        'quantity_range_low':500,
        'quantity_range_high':999,
        'color_1_cost':0.66,
        'color_2_cost':0.9,
        'color_3_cost':1.02,
        'color_4_cost':1.14,
        'color_5_cost':1.26,
        'color_6_cost':1.38,
        'color_additional_cost':0.12,
    },
    {
        'color': 'light',
        'quantity_range_low':1000,
        'quantity_range_high':2499,
        'color_1_cost':0.6,
        'color_2_cost':0.66,
        'color_3_cost':0.78,
        'color_4_cost':0.9,
        'color_5_cost':1.02,
        'color_6_cost':1.14,
        'color_additional_cost':0.12,
    },
    {
        'color': 'light',
        'quantity_range_low':2500,
        'quantity_range_high':4999,
        'color_1_cost':0.54,
        'color_2_cost':0.6,
        'color_3_cost':0.72,
        'color_4_cost':0.84,
        'color_5_cost':0.96,
        'color_6_cost':1.08,
        'color_additional_cost':0.12,
    },
    {
        'color': 'dark',
        'quantity_range_low':1,
        'quantity_range_high':23,
        'color_1_cost':5.4,
        'color_2_cost':5.7,
        'color_3_cost':6,
        'color_4_cost':6.3,
        'color_5_cost':6.6,
        'color_6_cost':None,
        'color_additional_cost':None,
    },
    {
        'color': 'dark',
        'quantity_range_low':24,
        'quantity_range_high':35,
        'color_1_cost':4.2,
        'color_2_cost':4.5,
        'color_3_cost':4.8,
        'color_4_cost':5.1,
        'color_5_cost':5.4,
        'color_6_cost':None,
        'color_additional_cost':None,
    },
    {
        'color': 'dark',
        'quantity_range_low':36,
        'quantity_range_high':71,
        'color_1_cost':2.22,
        'color_2_cost':2.52,
        'color_3_cost':2.82,
        'color_4_cost':3.12,
        'color_5_cost':3.42,
        'color_6_cost':3.72,
        'color_additional_cost':0.3,
    },
    {
        'color': 'dark',
        'quantity_range_low':72,
        'quantity_range_high':143,
        'color_1_cost':1.62,
        'color_2_cost':1.92,
        'color_3_cost':2.22,
        'color_4_cost':2.52,
        'color_5_cost':2.82,
        'color_6_cost':3.12,
        'color_additional_cost':0.3,
    },
    {
        'color': 'dark',
        'quantity_range_low':144,
        'quantity_range_high':287,
        'color_1_cost':1.44,
        'color_2_cost':1.74,
        'color_3_cost':2.04,
        'color_4_cost':2.34,
        'color_5_cost':2.64,
        'color_6_cost':2.94,
        'color_additional_cost':0.3,
    },
    {
        'color': 'dark',
        'quantity_range_low':288,
        'quantity_range_high':499,
        'color_1_cost':1.14,
        'color_2_cost':1.32,
        'color_3_cost':1.5,
        'color_4_cost':1.68,
        'color_5_cost':1.86,
        'color_6_cost':2.04,
        'color_additional_cost':0.18,
    },
    {
        'color': 'dark',
        'quantity_range_low':500,
        'quantity_range_high':999,
        'color_1_cost':1.02,
        'color_2_cost':1.14,
        'color_3_cost':1.26,
        'color_4_cost':1.38,
        'color_5_cost':1.5,
        'color_6_cost':1.62,
        'color_additional_cost':0.12,
    },
    {
        'color': 'dark',
        'quantity_range_low':1000,
        'quantity_range_high':2499,
        'color_1_cost':0.84,
        'color_2_cost':0.9,
        'color_3_cost':1.02,
        'color_4_cost':1.14,
        'color_5_cost':1.26,
        'color_6_cost':1.38,
        'color_additional_cost':0.12,
    },
    {
        'color': 'dark',
        'quantity_range_low':2500,
        'quantity_range_high':4999,
        'color_1_cost':0.78,
        'color_2_cost':0.84,
        'color_3_cost':0.96,
        'color_4_cost':1.08,
        'color_5_cost':1.2,
        'color_6_cost':1.32,
        'color_additional_cost':0.12,
    },
]

class Command(BaseCommand):
    help = 'populates the database PrintCost model with the print cost data'

    def handle(self, *args, **options):
        PrintCost.objects.all().delete()
        for cost in print_costs:
            PrintCost.objects.create(**cost)
        self.stdout.write('Successfully populated the database PrintCost model with the print cost data')
